# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      #- name: Bucket actions
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: 10
      #- run: npm i --no-optional --exact
      #- run: npm run build
      #  env:
      #`      CI: false

      - name: GitHub Run&Build Action
        # You may pin to the exact commit or the version.
        # uses: iranzo/gh-action-runpublish@694f10c00b1fae3385b4258a7f46348d5079b214
        uses: iranzo/gh-action-runpublish@0.0.4
        with:
          # override the default `gh-pages` deployment branch
          GH_PAGES_BRANCH: gh-pages # optional, default is gh-pages
          # override the default `content` folder for sources for website
          SOURCE_FOLDER: docs # optional, default is content
          # Set to any value to stop job before pushing to GH-Pages
          #DONOTPUBLISH: # optional, default is